# Generated by Django 5.1.5 on 2025-06-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekujące'), ('in_transit', 'W dostawie'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane')], default='pending', max_length=50),
        ),
    ]
