# Generated by Django 5.1.5 on 2025-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_driver_trucks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='trucks',
        ),
        migrations.AddField(
            model_name='order',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
